services:

  - title: "IEEE Transactions on Cybernetics 2024"
    role: Reviewer
    journal: y
    
  - title: "The 11th IEEE International Conference on Data Science and Advanced Analytics (DSAA 2024)"
    role: PC Member
    conference: y

  - title: "European Conference on Machine Learning and Principles and Practice of Knowledge Discovery in Databases (ECMLPKDD 2025)"
    role: PC Member
    conference: y

  - title: "The Thirteenth International Conference on Learning Representations （ICLR 2025）"
    role: PC Member
    conference: y
