services:
  - title: "Journal of Imaging"
    role: Guest Editor
    journal: y

  - title: "Electronics"
    role: Guest Editor
    journal: y
    
  - title: "TPAMI, AIJ, TNNLS, TCYB, TKDE, MLJ, KBS, ESWA, npj Digital Medicine, etc."
    role: Reviewer
    journal: y

  - title: "The Pacific-Asia Conference on Knowledge Discovery and Data Mining（PAKDD 2025）"
    role: Session Chair
    conference: y

  - title: "NeurIPS, ICLR, ICML, AAAI, IJCAI, KDD, UAI, AISTATS, ACML, ECMLPKDD, etc."
    role: PC Member
    conference: y
