services:
  - title: "XTM-Imaging: Explainable and Trustworthy Multimodal Imaging for Real-World Applications — Journal of Imaging"
    role: Guest Editor
    journal: y

  - title: "Advances and Applications in Blockchain Technology — Electronics"
    role: Guest Editor
    journal: y
    
  - title: "TPAMI, AIJ, TNNLS, TCYB, TKDE, MLJ, TMLR, npj Digital Medicine, etc."
    role: Reviewer
    journal: y

  - title: "The Pacific-Asia Conference on Knowledge Discovery and Data Mining（PAKDD 2025）"
    role: Session Chair
    conference: y

  - title: "IEEE International Conference on Behavioural and Social Computing, 2025"
    role: Session Chair
    conference: y

  - title: "IEEE International Conference on Image Processing, 2026"
    role: Session Organizer
    conference: y

  - title: "NeurIPS, ICLR, ICML, AAAI, IJCAI, KDD, UAI, AISTATS, ACML, ECMLPKDD, etc."
    role: PC Member
    conference: y
